# fly.toml app configuration file generated for anypointspeedwaygo on 2024-10-01T13:54:39-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'anypointspeedwaygo'
primary_region = 'ord'

[build]
  [build.args]
    GO_VERSION = '1.23.1'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
  http_timeout = "2400s"

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2

[[restart]]
  policy = "always"
  retries = 3
  processes = "app"